import type { Metadata } from "next";
import "./globals.css";
import 'antd/dist/reset.css';
import { cookies } from "next/headers";
import AppShell from "@/components/layout/AppShell";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { isValidToken } from '@/lib/auth';

export const metadata: Metadata = {
  title: "dev-insight",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const authenticated = isValidToken(cookieStore.get('token')?.value);

  return (
    <html lang="ko">
      <body>
        <AntdRegistry>
            <AppShell hasToken={authenticated}>
              {children}
            </AppShell>
        </AntdRegistry>
      </body>
    </html>
  );
}
