import type { Metadata } from "next";
import "./globals.css";
import 'antd/dist/reset.css';
import { cookies } from "next/headers"; 
import AntdLayout from "@/components/layout/AntdLayout";
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata: Metadata = {
  title: "dev-insight",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token');

  return (
    <html lang="ko">
      <body>
        <AntdRegistry>
            <AntdLayout hasToken={!!token}>
              {children}
            </AntdLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
